#account-service-service-monitoring.yaml
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: backend
spec:
  selector:
    app: account-service
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
