apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: bytebuilders-xyz
  namespace: database
spec:
  acme:
    # server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: diptaroy@appscode.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: bytebuilders-xyz-acme
    # ACME DNS-01 provider configurations
    solvers:
      # An empty 'selector' means that this solver matches all domains
      - selector: { }
        dns01:
          cloudflare:
            email: diptaroy@appscode.com
            apiTokenSecretRef:
              name: bytebuilders-xyz-cloudflare
              key: api-token