#pp-frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pp-frontend-service
  namespace: frontend
spec:
  selector:
    app: pp-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer