#enrollment-service-service-monitoring.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: enrollment-service
  labels:
    team: backend
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: enrollment-service
  endpoints:
    - port: "http"