#study-plan-service-service-monitoring.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: study-plan-service
  labels:
    team: backend
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: study-plan-service
  endpoints:
    - port: "http"