#backend-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: backend
type: Opaque
data:
  mariadb-root-password: cm9vdA==
  mariadb-user: ZWR1LXN5c3RlbS1kYi11c2Vy
  mariadb-user-password: ZWR1LXN5c3RlbS1kYi1wd2Q=
  mariadb-database: ZWR1LXN5c3RlbS1kYg==

