name: CI

# Określ, kiedy workflow ma być uruchamiany
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Definicja zadań (jobs)
jobs:
  build:
    # Określenie środowiska uruchomieniowego
    runs-on: ubuntu-latest

    # Kroki, które mają być wykonane w ramach zadania
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
